### ISSUE TITLE
Ellipsis (`…`) in commit message triggers multiple display bugs

### ISSUE THREAD

**Issue by homeworkprod** [MitMaro/git-interactive-rebase-tool#236] opened 2020-04-20 21:02 UTC
Given this commit message that contains an [ellipsis](https://en.wikipedia.org/wiki/Ellipsis):
```
Use URI literals to replace deprecated `Uri.uri("…")` calls
```

The UI of *girb* then:
- shows ` ~@ ` (with a leading and a trailing space) instead of `…` in the commit message
- indents the commit message after the one with the ellipsis
- indents the first empty line (consisting of, visibly, only `~`) (but not those after that)

Screenshot:
![girb_ellipsis-display-bug](https://user-images.githubusercontent.com/95277/79799153-4bc94b80-835a-11ea-89f3-cfdf40b62a78.png)

This was discovered using v1.1.0 and successfully reproduced with v1.2.1.

**Comment by glensc** [comment] 2020-04-22 12:42
@homeworkprod to me it seems like your locale is not UTF-8 enabled. show your `locale` command output prior rebase.

and this should fix your environment if that's the case:
```
export LC_ALL=en_US.UTF-8
```

**Comment by homeworkprod** [comment] 2020-04-22 21:40
@glensc, I think my locale is UTF-8-capable, though:
```sh
$ env | rg ^LC_
LC_TIME=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
```

And to make sure:
```sh
LC_ALL=en_US.UTF-8 git rebase -i HEAD~3
```
has the same effect as depicted in the screenshot above.

I have both locales installed on my system.

**Comment by homeworkprod** [comment] 2020-04-22 21:41
And for the terminal application: I could reproduce this in URxvt as well as Gnome Terminal.

**Comment by glensc** [comment] 2020-04-23 05:50
@homeworkprod works for me. macOS Catalina 10.15.4, iTerm2 (Build 3.3.8beta4)

![image](https://user-images.githubusercontent.com/199095/80063767-4da03400-853f-11ea-8b89-418a5029933a.png)

Perhaps try with other applications? In vim works?

**Comment by MitMaro** [comment] 2020-04-23 12:27
@homeworkprod , UTF-8 is fully supported, including combined characters, so I am surprised that you are having this issue.

Can you provide some information:

- What Linux Distro are you using?
- What font are you using for your terminal?

**Comment by homeworkprod** [comment] 2020-04-27 18:29
I can reproduce the faulty behavior on Debian 10 "Buster" and Ubuntu 19.04 "Eoan Ermine".

I have no idea, though, what font it uses. But I have the impression that Gnome Terminal at least uses a different font than URxvt.

I was able to narrow down the commit message to just `…` as a minimal example that triggers the behavior, so at least it doesn't have to be a combination with double quotes, backticks, etc.

Hope that helps.

**Comment by homeworkprod** [comment] 2020-04-27 18:34
The ellipsis is also displayed correctly in my terminals when shown directly as well as after piping the commit message into less, most, bat, and vim. This makes me assume that the font and the terminal are not the problem per se.

The fact that I'm only able to see this behavior in *girb* suggests that it's specific to it (or some library used by it).

If you can suggest similarly built applications, I can probably check them out. But at least `bat` (a Rust CLI tool) works fine in this regard.

**Comment by MitMaro** [comment] 2020-04-27 18:46
Thanks for the information @homeworkprod ! 

I was able to reproduce the bug on a Ubuntu like system, but I have no idea what might be causing it.

**Comment by MitMaro** [comment] 2020-04-27 19:21
I can't seem to reproduce the issue with the latest version of master. I think there are two possibilities.

The first, and most likely case, is that the build process that was used to create the apt packages were limited to what was available on TravisCI and that has caused issues in the past with bad/outdated dependencies.

The second is that it is caused by an outdated version of the Unicode library that is used by the project. I don't think this is the case, since things seem to be fine with the MacOS build.

I have since moved the project to use GitHub actions and to build on proper instances of Ubuntu and Debian. I have not yet done a full release wit this new process, but the [latest release](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/latest) does use the new build system. It does not seem to have the issue you described.

I will keep this issue open until the next release, so that the fix can be verified, but I believe this is fixed on master.

**Comment by MitMaro** [comment] 2020-04-27 19:21
Thanks again for the report! :)

**Comment by glensc** [comment] 2020-04-28 07:08
Perhaps the Unicode representation is wider than typical 3-4 bytes, and that's causing the issue.

whoever, if the problematic char is 'HORIZONTAL ELLIPSIS' (U+2026), then it's binary utf8 representation is just 3 bytes: `0xE2 0x80 0xA6 (e280a6)`

- https://www.fileformat.info/info/unicode/char/2026/index.htm

**Comment by MitMaro** [comment] 2020-04-28 12:00
> Perhaps the Unicode representation is wider than typical 3-4 bytes, and that's causing the issue.
> 
> whoever, if the problematic char is 'HORIZONTAL ELLIPSIS' (U+2026), then it's binary utf8 representation is just 3 bytes: `0xE2 0x80 0xA6 (e280a6)`
> 
> * [fileformat.info/info/unicode/char/2026/index.htm](https://www.fileformat.info/info/unicode/char/2026/index.htm)

That was my initial thought as well, but as you mention, 'HORIZONTAL ELLIPSIS' isn't exceptionally wide. Also, I was only able to reproduce the problem by using the `.deb` installer. With a local build, even with version 1.1.0, I could not reproduce the issue even with the same character.

In general, when there's a problem with Unicode support, it is as you initially stated. The terminal does not support or does not have enabled UTF-8.

**Comment by homeworkprod** [comment] 2020-05-05 22:22
Glad you could reproduce the issue!

Indeed I was using the Debian packages to install *girb* where I discovered the faulty behavior.

So I installed v1.2.1 from source and checked again: the issue does *not* appear!

**Comment by MitMaro** [comment] 2021-02-05 00:41
As of version 2.0.0, this project is no longer dependent on curses, so Unicode support should be even better than it was before.

**Closed by MitMaro** 2021-02-05 00:41 UTC
Labels: bug, fixed-in-dev
