### ISSUE TITLE
Use one uniq name for the executable instead of different ones

### ISSUE THREAD

**Issue by jnachtigall** [MitMaro/git-interactive-rebase-tool#45] opened 2018-03-05 09:45 UTC
1. cargo calls it `git-interactive-rebase-tool`.
2. The `usage` refers to `git-interactive`
3. And the README.md has just `interactive-rebase-tool

and depending on which name is actually used there are different `git configure` commands in the README.md

![image](https://user-images.githubusercontent.com/3307404/36968233-430dc348-2062-11e8-92c1-d81eff92eb5b.png)

I think it would be good to settle on one uniq name for the program and use this across all OSes.

**Comment by MitMaro** [comment] 2018-03-05 15:22
A agree, I've been dealing with that a fair bit.

Initially the project used the full name `git-interactive-rebase-tool` but this had the side effect of adding a command `interactive-rebase` to git through `git interactive-rebase`. I can't find the reference now, but essentially it's caused by the git command line tool searching the path for any executable that starts with `git-`.

I thought I had mitigated all the cases, but I didn't think of the one you mentioned in pull request #44 . I think this can be fixed by providing a configuration option in `Cargo.toml`.

**Comment by MitMaro** [comment] 2018-03-05 15:25
I think that https://doc.rust-lang.org/cargo/reference/manifest.html#configuring-a-target might be of some help here.

**Closed** 2018-03-31 21:50 UTC

**Comment by MitMaro** [comment] 2018-03-31 21:55
This should be resolved now. The name of the project remains `git-interactive-rebase-tool` the executable is called `interactive-rebase-tool`.
